### ISSUE TITLE
better support for sub-classing in UUID

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/uuid-api#134]
Revert the patch used for subclassing Publications (Publications show up as Datasets) and allow Publication entities directly.  

This should include any SQL to update the existing databases to remove/change any data.

**Comment by kburke** [comment]
I've updated **_some_** of the uuids.ENTITY_TYPE rows in DEV using the query that follows.  If the data migration and the Pull Request look okay, I will execute it for the rest of the rows, then TEST & PROD in coordination with the PR migration.

```
WITH DatasetToPublicationUUIDs AS (
	SELECT DISTINCT u.UUID
	FROM uuids_attributes AS ua
		INNER JOIN uuids AS u ON ua.UUID=u.UUID
	WHERE ua.ENTITY_CLASS_METADATA IS NOT NULL
	  AND u.ENTITY_TYPE='DATASET'
	  AND LEFT(u.UUID,1) IN ('0','1','2','3','4','5','6','7','8','9')
)
UPDATE `uuids`
SET `ENTITY_TYPE` = 'PUBLICATION'
WHERE `UUID` IN (SELECT DISTINCT UUID FROM DatasetToPublicationUUIDs);
```
